version: '3.3'
services:
  library-database:
    image: postgres:13
    environment:
      - POSTGRES_DB=library_database
      - POSTGRES_USER=santi
      - POSTGRES_PASSWORD=1603
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
      
volumes:
  postgres_data:
    external: true